/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lourenco
 */
public class Frmradiobutton extends javax.swing.JFrame {

    /**
     * Creates new form Frmradiobutton
     */
    public Frmradiobutton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbltitulo = new javax.swing.JLabel();
        lblresposta = new javax.swing.JLabel();
        txtfresposta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbjava = new javax.swing.JRadioButton();
        rbjs = new javax.swing.JRadioButton();
        rbphp = new javax.swing.JRadioButton();
        btnescolher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbltitulo.setText("Exemplo RadioButton");

        lblresposta.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblresposta.setText("Resposta:");

        txtfresposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfrespostaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Linguagens de programação"));

        buttonGroup1.add(rbjava);
        rbjava.setText("Java");
        rbjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbjavaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbjs);
        rbjs.setText("JavaScript");
        rbjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbjsActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbphp);
        rbphp.setText("PHP");
        rbphp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbphpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbjava)
                .addGap(18, 18, 18)
                .addComponent(rbjs)
                .addGap(18, 18, 18)
                .addComponent(rbphp)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbjava)
                    .addComponent(rbjs)
                    .addComponent(rbphp))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnescolher.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btnescolher.setText("Escolher");
        btnescolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnescolherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblresposta)
                        .addGap(32, 32, 32)
                        .addComponent(txtfresposta)
                        .addGap(101, 101, 101))))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnescolher)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblresposta)
                    .addComponent(txtfresposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnescolher)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfrespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfrespostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfrespostaActionPerformed

    private void rbjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbjavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbjavaActionPerformed

    private void rbjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbjsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbjsActionPerformed

    private void rbphpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbphpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbphpActionPerformed

    private void btnescolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnescolherActionPerformed
        // TODO add your handling code here:
        if(rbjava.isSelected() == true){
            //A opção escolhida foi Java
            txtfresposta.setText("Java");
        }else if(rbjs.isSelected() == true){
            //A opção escolhida foi JavaScript
            txtfresposta.setText(rbjs.getText());
        }else if(rbphp.isSelected() == true){
            //A opção escolhida foi PHP
            txtfresposta.setText("PHP");
    }
    }//GEN-LAST:event_btnescolherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmradiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmradiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmradiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmradiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmradiobutton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnescolher;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblresposta;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JRadioButton rbjava;
    private javax.swing.JRadioButton rbjs;
    private javax.swing.JRadioButton rbphp;
    private javax.swing.JTextField txtfresposta;
    // End of variables declaration//GEN-END:variables
}
